---

- name: Ensure application directory exists
  ansible.builtin.file:
    path: "{{ app_dir_in_vm }}"
    state: directory
    mode: '0755'
    owner: vagrant
    group: vagrant
  tags: [ 'app_clone' ]

- name: Clone or update the application repository
  ansible.builtin.git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dir_in_vm }}"
    version: master
    force: yes
  become: yes
  become_user: vagrant
  tags: [ 'app_clone' ]

- name: Verify cloned repository content (optional, for debugging)
  ansible.builtin.command: "ls -la {{ app_dir_in_vm }}"
  register: ls_output
  changed_when: false
  tags: [ 'app_clone' ]

- name: Print cloned repository content
  ansible.builtin.debug:
    msg: "{{ ls_output.stdout_lines }}"
  tags: [ 'app_clone' ]
