version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ipnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb/yolomy
      - UPLOAD_DIR=/usr/src/app/public/images
    volumes:
      - yolomy-uploads:/usr/src/app/public/images
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      ipnet:
        aliases:
          - ipbackend
          - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - yolomy-data:/data/db
    networks:
      - ipnet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  yolomy-data:
  yolomy-uploads:

networks:
  ipnet:
    driver: bridge