---

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [ 'common' ]

- name: Install common packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - build-essential
    state: present
  tags: [ 'common' ]

- name: Ensure Python 3 and pip are installed (needed for some Ansible modules, e.g., docker)
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
  tags: [ 'common' ]
