---

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [ 'docker' ]

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags: [ 'docker' ]

- name: Update apt package cache again after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes
  tags: [ 'docker' ]

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: [ 'docker' ]

- name: Ensure Docker service is running and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  tags: [ 'docker' ]

- name: Add 'vagrant' user to the 'docker' group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes
  tags: [ 'docker' ]

- name: Restart Docker service to apply group changes
  ansible.builtin.systemd:
    name: docker
    state: restarted
  tags: [ 'docker' ]