

- name: Provision Vagrant VM and Deploy MERN Application
  hosts: all
  become: yes

  roles:
    - role: common 
      tags: ["common", "setup"]

    - role: docker 
      tags: ["docker", "setup"]

    - role: clone 
      tags: ["app_clone", "deploy"]

    - role: mongodb
      tags: ["mongodb", "containers", "deploy"]

    - role: backend
      tags: ["backend", "containers", "deploy"]

    - role: frontend
      tags: ["frontend", "containers", "deploy"]

    - role: docker
      tags: ["docker_compose", "deploy"]

