

- name: Provision Vagrant VM and Deploy YOLOMY Application
  hosts: all
  become: yes

  roles:
    - role: common 
    - role: docker 
    - role: clone 
    - role: mongodb
    - role: backend
    - role: frontend
